### ISSUE TITLE
Guide

### ISSUE THREAD

**Issue by ComputerApp1234** [mrbesen/ClashRoyale-Bot#1]
Vielen Dank für die großartige Arbeit!
Könntest du mir vielleicht erklären, wie ich als absoluter "Anfänger" den Bot benutzen kann und was es dabei zu beachten gilt?

**Comment by mrbesen** [comment]
I made a [video](https://vimeo.com/222811186) where the bot is shown in action. Just watch it, most problems should be solved. d2db04ba3b897d13deabf4ff4d9cb8c3e536924d
